version: '3.8'

name: linkedin-reverse-search

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: link-backend
    ports:
      - "3008:3008"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./ssl:/app/ssl
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3008"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: link-frontend
    ports:
      - "3009:3009"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3009"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge 